### ISSUE TITLE
Please tag a new release version

### ISSUE THREAD

**Issue by dominykas** [jenkinsci/commons-text-api-plugin#14]
### What feature do you want to see added?

Not a feature per se, but it would be nice if there was a brand new release with a disambiguated version number. The latest release `3.12.0-36.vd97de6465d5b_` is considered older than `3.12.0.0` by some tools (e.g. simple string sorting, but also by [renovate](https://github.com/renovatebot/renovate)). [Dependabot clearly thinks differently](https://github.com/jenkinsci/commons-text-api-plugin/pull/9).

If there was a `3.12.1-something.something`, the ambiguity would go away.

**Comment by sghill** [comment]
@dominykas I think this issue is about changing the versioning for jenkinsci/commons-lang3-api-plugin, not this plugin. Could you open it there or in the Jenkins JIRA?

**Comment by dominykas** [comment]
Oh, sorry, E_TOO_MANY_OPEN_TABS :D
